export const KEYS = [
  { name: "C", enharmonic: null },
  { name: "C#", enharmonic: "Db" },
  { name: "D", enharmonic: null },
  { name: "D#", enharmonic: "Eb" },
  { name: "E", enharmonic: null },
  { name: "F", enharmonic: null },
  { name: "F#", enharmonic: "Gb" },
  { name: "G", enharmonic: null },
  { name: "G#", enharmonic: "Ab" },
  { name: "A", enharmonic: null },
  { name: "A#", enharmonic: "Bb" },
  { name: "B", enharmonic: null },
]

export const ALL_MODES = [
  "Major (Ionian)",
  "Dorian",
  "Phrygian",
  "Lydian",
  "Mixolydian",
  "Aeolian (Minor)",
  "Locrian",
  "Major Pentatonic",
  "Minor Pentatonic",
  "Minor Blues",
  "Major Blues",
  "Melodic Minor",
  "Harmonic Minor",
  "Hungarian Scale",
]

export const TIME_SIGNATURES = ["2/4", "3/4", "4/4", "6/8", "9/8", "12/8", "5/4", "7/4", "5/8", "7/8"]

export const CIRCLE_OF_FIFTHS_MAJOR = ["C", "G", "D", "A", "E", "B", "F#/Gb", "Db", "Ab", "Eb", "Bb", "F"]
export const CIRCLE_OF_FIFTHS_MINOR = ["Am", "Em", "Bm", "F#m", "C#m", "G#m", "D#m/Ebm", "Bbm", "Fm", "Cm", "Gm", "Dm"]

export const CHORD_PROGRESSIONS = {
  C: [
    { roman: "I", chord: "C" },
    { roman: "ii", chord: "Dm" },
    { roman: "iii", chord: "Em" },
    { roman: "IV", chord: "F" },
    { roman: "V", chord: "G" },
    { roman: "vi", chord: "Am" },
    { roman: "vii°", chord: "B°" },
  ],
  G: [
    { roman: "I", chord: "G" },
    { roman: "ii", chord: "Am" },
    { roman: "iii", chord: "Bm" },
    { roman: "IV", chord: "C" },
    { roman: "V", chord: "D" },
    { roman: "vi", chord: "Em" },
    { roman: "vii°", chord: "F#°" },
  ],
  D: [
    { roman: "I", chord: "D" },
    { roman: "ii", chord: "Em" },
    { roman: "iii", chord: "F#m" },
    { roman: "IV", chord: "G" },
    { roman: "V", chord: "A" },
    { roman: "vi", chord: "Bm" },
    { roman: "vii°", chord: "C#°" },
  ],
  A: [
    { roman: "I", chord: "A" },
    { roman: "ii", chord: "Bm" },
    { roman: "iii", chord: "C#m" },
    { roman: "IV", chord: "D" },
    { roman: "V", chord: "E" },
    { roman: "vi", chord: "F#m" },
    { roman: "vii°", chord: "G#°" },
  ],
  E: [
    { roman: "I", chord: "E" },
    { roman: "ii", chord: "F#m" },
    { roman: "iii", chord: "G#m" },
    { roman: "IV", chord: "A" },
    { roman: "V", chord: "B" },
    { roman: "vi", chord: "C#m" },
    { roman: "vii°", chord: "D#°" },
  ],
  B: [
    { roman: "I", chord: "B" },
    { roman: "ii", chord: "C#m" },
    { roman: "iii", chord: "D#m" },
    { roman: "IV", chord: "E" },
    { roman: "V", chord: "F#" },
    { roman: "vi", chord: "G#m" },
    { roman: "vii°", chord: "A#°" },
  ],
  "F#/Gb": [
    { roman: "I", chord: "F#" },
    { roman: "ii", chord: "G#m" },
    { roman: "iii", chord: "A#m" },
    { roman: "IV", chord: "B" },
    { roman: "V", chord: "C#" },
    { roman: "vi", chord: "D#m" },
    { roman: "vii°", chord: "E#°" },
  ],
  Db: [
    { roman: "I", chord: "Db" },
    { roman: "ii", chord: "Ebm" },
    { roman: "iii", chord: "Fm" },
    { roman: "IV", chord: "Gb" },
    { roman: "V", chord: "Ab" },
    { roman: "vi", chord: "Bbm" },
    { roman: "vii°", chord: "C°" },
  ],
  Ab: [
    { roman: "I", chord: "Ab" },
    { roman: "ii", chord: "Bbm" },
    { roman: "iii", chord: "Cm" },
    { roman: "IV", chord: "Db" },
    { roman: "V", chord: "Eb" },
    { roman: "vi", chord: "Fm" },
    { roman: "vii°", chord: "G°" },
  ],
  Eb: [
    { roman: "I", chord: "Eb" },
    { roman: "ii", chord: "Fm" },
    { roman: "iii", chord: "Gm" },
    { roman: "IV", chord: "Ab" },
    { roman: "V", chord: "Bb" },
    { roman: "vi", chord: "Cm" },
    { roman: "vii°", chord: "D°" },
  ],
  Bb: [
    { roman: "I", chord: "Bb" },
    { roman: "ii", chord: "Cm" },
    { roman: "iii", chord: "Dm" },
    { roman: "IV", chord: "Eb" },
    { roman: "V", chord: "F" },
    { roman: "vi", chord: "Gm" },
    { roman: "vii°", chord: "A°" },
  ],
  F: [
    { roman: "I", chord: "F" },
    { roman: "ii", chord: "Gm" },
    { roman: "iii", chord: "Am" },
    { roman: "IV", chord: "Bb" },
    { roman: "V", chord: "C" },
    { roman: "vi", chord: "Dm" },
    { roman: "vii°", chord: "E°" },
  ],
  Am: [
    { roman: "i", chord: "Am" },
    { roman: "ii°", chord: "B°" },
    { roman: "III", chord: "C" },
    { roman: "iv", chord: "Dm" },
    { roman: "v", chord: "Em" },
    { roman: "VI", chord: "F" },
    { roman: "VII", chord: "G" },
  ],
  Em: [
    { roman: "i", chord: "Em" },
    { roman: "ii°", chord: "F#°" },
    { roman: "III", chord: "G" },
    { roman: "iv", chord: "Am" },
    { roman: "v", chord: "Bm" },
    { roman: "VI", chord: "C" },
    { roman: "VII", chord: "D" },
  ],
  Bm: [
    { roman: "i", chord: "Bm" },
    { roman: "ii°", chord: "C#°" },
    { roman: "III", chord: "D" },
    { roman: "iv", chord: "Em" },
    { roman: "v", chord: "F#m" },
    { roman: "VI", chord: "G" },
    { roman: "VII", chord: "A" },
  ],
  "F#m": [
    { roman: "i", chord: "F#m" },
    { roman: "ii°", chord: "G#°" },
    { roman: "III", chord: "A" },
    { roman: "iv", chord: "Bm" },
    { roman: "v", chord: "C#m" },
    { roman: "VI", chord: "D" },
    { roman: "VII", chord: "E" },
  ],
  "C#m": [
    { roman: "i", chord: "C#m" },
    { roman: "ii°", chord: "D#°" },
    { roman: "III", chord: "E" },
    { roman: "iv", chord: "F#m" },
    { roman: "v", chord: "G#m" },
    { roman: "VI", chord: "A" },
    { roman: "VII", chord: "B" },
  ],
  "G#m": [
    { roman: "i", chord: "G#m" },
    { roman: "ii°", chord: "A#°" },
    { roman: "III", chord: "B" },
    { roman: "iv", chord: "C#m" },
    { roman: "v", chord: "D#m" },
    { roman: "VI", chord: "E" },
    { roman: "VII", chord: "F#" },
  ],
  "D#m/Ebm": [
    { roman: "i", chord: "D#m" },
    { roman: "ii°", chord: "E#°" },
    { roman: "III", chord: "F#" },
    { roman: "iv", chord: "G#m" },
    { roman: "v", chord: "A#m" },
    { roman: "VI", chord: "B" },
    { roman: "VII", chord: "C#" },
  ],
  Bbm: [
    { roman: "i", chord: "Bbm" },
    { roman: "ii°", chord: "C°" },
    { roman: "iii", chord: "Db" },
    { roman: "iv", chord: "Ebm" },
    { roman: "v", chord: "Fm" },
    { roman: "vi", chord: "Gb" },
    { roman: "VII", chord: "Ab" },
  ],
  Fm: [
    { roman: "i", chord: "Fm" },
    { roman: "ii°", chord: "G°" },
    { roman: "iii", chord: "Ab" },
    { roman: "iv", chord: "Bbm" },
    { roman: "v", chord: "Cm" },
    { roman: "vi", chord: "Db" },
    { roman: "VII", chord: "Eb" },
  ],
  Cm: [
    { roman: "i", chord: "Cm" },
    { roman: "ii°", chord: "D°" },
    { roman: "iii", chord: "Eb" },
    { roman: "iv", chord: "Fm" },
    { roman: "v", chord: "Gm" },
    { roman: "vi", chord: "Ab" },
    { roman: "VII", chord: "Bb" },
  ],
  Gm: [
    { roman: "i", chord: "Gm" },
    { roman: "ii°", chord: "A°" },
    { roman: "iii", chord: "Bb" },
    { roman: "iv", chord: "Cm" },
    { roman: "v", chord: "Dm" },
    { roman: "vi", chord: "Eb" },
    { roman: "VII", chord: "F" },
  ],
  Dm: [
    { roman: "i", chord: "Dm" },
    { roman: "ii°", chord: "E°" },
    { roman: "iii", chord: "F" },
    { roman: "iv", chord: "Gm" },
    { roman: "v", chord: "Am" },
    { roman: "vi", chord: "Bb" },
    { roman: "VII", chord: "C" },
  ],
}

export const CHORD_COLORS = [
  "rgb(16, 185, 129)",
  "rgb(59, 130, 246)",
  "rgb(147, 51, 234)",
  "rgb(56, 189, 248)",
  "rgb(236, 72, 153)",
  "rgb(251, 191, 36)",
  "rgb(148, 163, 184)",
]

export const CHORD_FUNCTIONS = {
  major: ["tonic", "supertonic", "mediant", "subdominant", "dominant", "submediant", "leading tone"],
  minor: ["tonic", "supertonic", "mediant", "subdominant", "dominant", "submediant", "subtonic"],
}

export const KEY_RELATIONSHIPS = {
  C: { relative: "Am", parallel: "Cm" },
  G: { relative: "Em", parallel: "Gm" },
  D: { relative: "Bm", parallel: "Dm" },
  A: { relative: "F#m", parallel: "Am" },
  E: { relative: "C#m", parallel: "Em" },
  B: { relative: "G#m", parallel: "Bm" },
  "F#/Gb": { relative: "D#m/Ebm", parallel: "F#m/Gbm" },
  Db: { relative: "Bbm", parallel: "Dbm" },
  Ab: { relative: "Fm", parallel: "Abm" },
  Eb: { relative: "Cm", parallel: "Ebm" },
  Bb: { relative: "Gm", parallel: "Bbm" },
  F: { relative: "Dm", parallel: "Fm" },
  Am: { relative: "C", parallel: "A" },
  Em: { relative: "G", parallel: "E" },
  Bm: { relative: "D", parallel: "B" },
  "F#m": { relative: "A", parallel: "F#" },
  "C#m": { relative: "E", parallel: "C#" },
  "G#m": { relative: "B", parallel: "G#" },
  "D#m/Ebm": { relative: "F#/Gb", parallel: "D#/Eb" },
  Bbm: { relative: "Db", parallel: "Bb" },
  Fm: { relative: "Ab", parallel: "F" },
  Cm: { relative: "Eb", parallel: "C" },
  Gm: { relative: "Bb", parallel: "G" },
  Dm: { relative: "F", parallel: "D" },
}

export const GUITAR_STRINGS = ["E", "B", "G", "D", "A", "E"]
export const CHROMATIC_NOTES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]

export const STRING_STARTING_NOTES = {
  E: 4,
  B: 11,
  G: 7,
  D: 2,
  A: 9,
  E_low: 4,
}

export const CHROMATIC_NOTE_COLORS = {
  C: "rgb(244, 114, 182)",
  "C#": "rgb(217, 179, 140)",
  D: "rgb(163, 230, 53)",
  "D#": "rgb(34, 197, 94)",
  E: "rgb(16, 185, 129)",
  F: "rgb(110, 231, 183)",
  "F#": "rgb(103, 232, 249)",
  G: "rgb(59, 130, 246)",
  "G#": "rgb(147, 51, 234)",
  A: "rgb(168, 85, 247)",
  "A#": "rgb(236, 72, 153)",
  B: "rgb(249, 115, 22)",
}

export const SCALE_FORMULAS = {
  "Major (Ionian)": [0, 2, 4, 5, 7, 9, 11],
  Dorian: [0, 2, 3, 5, 7, 9, 10],
  Phrygian: [0, 1, 3, 5, 7, 8, 10],
  Lydian: [0, 2, 4, 6, 7, 9, 11],
  Mixolydian: [0, 2, 4, 5, 7, 9, 10],
  "Aeolian (Minor)": [0, 2, 3, 5, 7, 8, 10],
  Locrian: [0, 1, 3, 5, 6, 8, 10],
  "Major Pentatonic": [0, 2, 4, 7, 9],
  "Minor Pentatonic": [0, 3, 5, 7, 10],
  "Minor Blues": [0, 3, 5, 6, 7, 10],
  "Major Blues": [0, 2, 3, 4, 7, 9],
  "Melodic Minor": [0, 2, 3, 5, 7, 9, 11],
  "Harmonic Minor": [0, 2, 3, 5, 7, 8, 11],
  "Hungarian Scale": [0, 2, 3, 6, 7, 8, 11],
}